version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: rabbitmq:3-management-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: ./tasks/test.sh
      - run: ./tasks/coverage-publish.sh
